services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    BackendExtBundle\Controller\:
        resource: "../src/Controller"
        public: true
        tags: ["controller.service_arguments"]

    # BackendExtBundle\EventListener\PimcoreAdminListener:
    #     tags:
    #         - {
    #               name: "kernel.event_listener",
    #               event: "pimcore.bundle_manager.paths.js",
    #               method: "addJSFiles",
    #           }
